version: '3.8'
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: coursesdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    image: gautamgovind/courses-api:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/coursesdb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    image: gautamgovind/courses-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata:
